site_name: LightInject

pages:
- Home: index.md
- Extensions:
    - Interception: interception.md
    - AutoFactory: autofactory.md
    - Annotation: annotation.md
- Integrations:
    - xUnit: xunit.md 
    - Web: web.md
- Side Project:
    - LightMock : lightmock.md   
 