site_name: LightInject

pages:
- Home: index.md
- Extensions:
    - Interception: interception.md
    - AutoFactory: autofactory.md
    - Annotation: annotation.md
- Integrations:
    - xUnit: xunit.md 
    - Web: web.md
    - Microsoft DependencyInjection : microsoft.dependencyinjection.md
- Examples:
    - Web Api Request Logging: webapirequestlogging.md    
- Side Projects:
    - LightMock : lightmock.md   
 