site_name: LightInject

pages:
- Home: index.md
- Patterns : designpatterns.md
- Extensions:
    - Interception: interception.md
    - AutoFactory: autofactory.md
    - Annotation: annotation.md
- Integrations:
    - xUnit: xunit.md 
    - Web: web.md
    - Mvc: mvc.md
    - WCF: wcf.md
    - Web Api: webapi.md
    - Nancy: nancy.md
    - Microsoft DependencyInjection : microsoft.dependencyinjection.md    
- Examples:
    - Web Api Request Logging: webapirequestlogging.md    
    - Transactions and Testing: transactions.md
- Side Projects:
    - LightMock : lightmock.md   
- About: 
    - Licence : licence.md             
 